server:
  port: 9297
  
spring:
  application:
    name: telebet-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajlomatech2023/telebet-casino
          clone-on-start: true  