spring:
  datasource:
    url: jdbc:mysql://localhost:3306/telebet
    username: telebet
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
    
server:
  port: 9092